version: "3.9"

services:
  bot:
    image: golang:1.20.5-alpine3.18
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./:/bot/
    working_dir: /bot/
    command: go run ./cmd/vault-bot/main.go

  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    ports:
      - "${DB_HOST:-127.0.0.1}:${DB_PORT:-5432}:${DB_PORT:-5432}"
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
