version: "3.9"

services:
  bot:
    image: golang:1.20-alpine3.18
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./:/bot/
    working_dir: /bot/
    command: go run ./cmd/vault/main.go

  postgres:
    image: postgres:15.3-alpine3.18
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
