name: CI

on:
  push:
    branches: [main]
    paths: ["**.go"]
  pull_request:
    branches: [main]
    paths: ["**.go"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          cache: "false"

      - name: Set up Go linters
        uses: golangci/golangci-lint-action@v3
        with:
          version: "v1.53"
          args: --timeout=10m
